from src.pre_built.sorting import sort_by


def test_sort_by_criteria():
    jobs = [
        {
            "job_title": "Marketing",
            "company": "Relief",
            "state": "NY",
            "city": "New York",
            "min_salary": "",
            "max_salary": "30000",
            "job_desc": "Marketing operations of the company.",
            "industry": "Finance",
            "rating": "4.0",
            "date_posted": "2020-05-08",
            "valid_until": "2020-06-07",
            "job_type": "FULL_TIME",
            "id": "0",
        },
        {
            "job_title": "Registered Nurse",
            "company": "Queens Boulevard Endoscopy Center",
            "state": "NY",
            "city": "Rego Park",
            "min_salary": "30000",
            "max_salary": "",
            "job_desc": "Full-Time Registered Nurse!",
            "industry": "",
            "rating": "3.0",
            "date_posted": "2020-04-25",
            "valid_until": "2020-06-07",
            "job_type": "FULL_TIME",
            "id": "1",
        },
        {
            "job_title": "Dental Hygienist",
            "company": "Batista Dental",
            "state": "NJ",
            "city": "West New York",
            "min_salary": "21600",
            "max_salary": "42000",
            "job_desc": "Part-time or Full-timedental...",
            "industry": "",
            "rating": "",
            "date_posted": "2020-05-02",
            "valid_until": "2020-06-07",
            "job_type": "PART_TIME",
            "id": "2",
        },
        {
            "job_title": "Senior Salesforce Developer",
            "company": "National Debt Relief",
            "state": "NY",
            "city": "New York",
            "min_salary": "44587",
            "max_salary": "82162",
            "job_desc": "Principle Duties & Responsibilities: ...",
            "industry": "Finance",
            "rating": "4.0",
            "date_posted": "2020-05-08",
            "valid_until": "2020-06-07",
            "job_type": "FULL_TIME",
            "id": "3",
        },
        {
            "job_title": "DEPUTY EXECUTIVE DIRECTOR",
            "company": "National Advocates for Pregnant Women",
            "state": "NY",
            "city": "New York",
            "min_salary": "125410",
            "max_salary": "212901",
            "job_desc": "For FULL Job Announcement, visit our website.",
            "industry": "",
            "rating": "",
            "date_posted": "2020-04-28",
            "valid_until": "2020-06-07",
            "job_type": "FULL_TIME",
            "id": "4",
        },
    ]

    expected_result_by_min_salary = [
        {
            "city": "West New York",
            "company": "Batista Dental",
            "date_posted": "2020-05-02",
            "id": "2",
            "industry": "",
            "job_desc": "Part-time or Full-timedental...",
            "job_title": "Dental Hygienist",
            "job_type": "PART_TIME",
            "max_salary": "42000",
            "min_salary": "21600",
            "rating": "",
            "state": "NJ",
            "valid_until": "2020-06-07",
        },
        {
            "city": "Rego Park",
            "company": "Queens Boulevard Endoscopy Center",
            "date_posted": "2020-04-25",
            "id": "1",
            "industry": "",
            "job_desc": "Full-Time Registered Nurse!",
            "job_title": "Registered Nurse",
            "job_type": "FULL_TIME",
            "max_salary": "",
            "min_salary": "30000",
            "rating": "3.0",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
        {
            "city": "New York",
            "company": "National Debt Relief",
            "date_posted": "2020-05-08",
            "id": "3",
            "industry": "Finance",
            "job_desc": "Principle Duties & Responsibilities: ...",
            "job_title": "Senior Salesforce Developer",
            "job_type": "FULL_TIME",
            "max_salary": "82162",
            "min_salary": "44587",
            "rating": "4.0",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
        {
            "city": "New York",
            "company": "National Advocates for Pregnant Women",
            "date_posted": "2020-04-28",
            "id": "4",
            "industry": "",
            "job_desc": "For FULL Job Announcement, visit our website.",
            "job_title": "DEPUTY EXECUTIVE DIRECTOR",
            "job_type": "FULL_TIME",
            "max_salary": "212901",
            "min_salary": "125410",
            "rating": "",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
        {
            "city": "New York",
            "company": "Relief",
            "date_posted": "2020-05-08",
            "id": "0",
            "industry": "Finance",
            "job_desc": "Marketing operations of the company.",
            "job_title": "Marketing",
            "job_type": "FULL_TIME",
            "max_salary": "30000",
            "min_salary": "",
            "rating": "4.0",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
    ]

    expected_result_by_max_salary = [
        {
            "city": "New York",
            "company": "National Advocates for Pregnant Women",
            "date_posted": "2020-04-28",
            "id": "4",
            "industry": "",
            "job_desc": "For FULL Job Announcement, visit our website.",
            "job_title": "DEPUTY EXECUTIVE DIRECTOR",
            "job_type": "FULL_TIME",
            "max_salary": "212901",
            "min_salary": "125410",
            "rating": "",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
        {
            "city": "New York",
            "company": "National Debt Relief",
            "date_posted": "2020-05-08",
            "id": "3",
            "industry": "Finance",
            "job_desc": "Principle Duties & Responsibilities: ...",
            "job_title": "Senior Salesforce Developer",
            "job_type": "FULL_TIME",
            "max_salary": "82162",
            "min_salary": "44587",
            "rating": "4.0",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
        {
            "city": "West New York",
            "company": "Batista Dental",
            "date_posted": "2020-05-02",
            "id": "2",
            "industry": "",
            "job_desc": "Part-time or Full-timedental...",
            "job_title": "Dental Hygienist",
            "job_type": "PART_TIME",
            "max_salary": "42000",
            "min_salary": "21600",
            "rating": "",
            "state": "NJ",
            "valid_until": "2020-06-07",
        },
        {
            "city": "New York",
            "company": "Relief",
            "date_posted": "2020-05-08",
            "id": "0",
            "industry": "Finance",
            "job_desc": "Marketing operations of the company.",
            "job_title": "Marketing",
            "job_type": "FULL_TIME",
            "max_salary": "30000",
            "min_salary": "",
            "rating": "4.0",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
        {
            "city": "Rego Park",
            "company": "Queens Boulevard Endoscopy Center",
            "date_posted": "2020-04-25",
            "id": "1",
            "industry": "",
            "job_desc": "Full-Time Registered Nurse!",
            "job_title": "Registered Nurse",
            "job_type": "FULL_TIME",
            "max_salary": "",
            "min_salary": "30000",
            "rating": "3.0",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
    ]

    expected_result_by_date_posted = [
        {
            "city": "New York",
            "company": "National Debt Relief",
            "date_posted": "2020-05-08",
            "id": "3",
            "industry": "Finance",
            "job_desc": "Principle Duties & Responsibilities: ...",
            "job_title": "Senior Salesforce Developer",
            "job_type": "FULL_TIME",
            "max_salary": "82162",
            "min_salary": "44587",
            "rating": "4.0",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
        {
            "city": "New York",
            "company": "Relief",
            "date_posted": "2020-05-08",
            "id": "0",
            "industry": "Finance",
            "job_desc": "Marketing operations of the company.",
            "job_title": "Marketing",
            "job_type": "FULL_TIME",
            "max_salary": "30000",
            "min_salary": "",
            "rating": "4.0",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
        {
            "city": "West New York",
            "company": "Batista Dental",
            "date_posted": "2020-05-02",
            "id": "2",
            "industry": "",
            "job_desc": "Part-time or Full-timedental...",
            "job_title": "Dental Hygienist",
            "job_type": "PART_TIME",
            "max_salary": "42000",
            "min_salary": "21600",
            "rating": "",
            "state": "NJ",
            "valid_until": "2020-06-07",
        },
        {
            "city": "New York",
            "company": "National Advocates for Pregnant Women",
            "date_posted": "2020-04-28",
            "id": "4",
            "industry": "",
            "job_desc": "For FULL Job Announcement, visit our website.",
            "job_title": "DEPUTY EXECUTIVE DIRECTOR",
            "job_type": "FULL_TIME",
            "max_salary": "212901",
            "min_salary": "125410",
            "rating": "",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
        {
            "city": "Rego Park",
            "company": "Queens Boulevard Endoscopy Center",
            "date_posted": "2020-04-25",
            "id": "1",
            "industry": "",
            "job_desc": "Full-Time Registered Nurse!",
            "job_title": "Registered Nurse",
            "job_type": "FULL_TIME",
            "max_salary": "",
            "min_salary": "30000",
            "rating": "3.0",
            "state": "NY",
            "valid_until": "2020-06-07",
        },
    ]

    sort_by(jobs, "min_salary")
    assert jobs == expected_result_by_min_salary

    sort_by(jobs, "max_salary")
    assert jobs == expected_result_by_max_salary

    sort_by(jobs, "date_posted")
    assert jobs == expected_result_by_date_posted
